model:
    arch: frrnB
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    path: /Users/hovo/Downloads/dataset/
training:
    n_workers: 64
    train_iters: 85000
    batch_size: 2
    val_interval: 500
    print_interval: 25
    optimizer:
        name: sgd
        lr: 1.0e-4
    l_rate: 1.0e-4
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
        name: 'multi_step'
        milestones: [10000,30000]
        gamma: 0.1
    momentum: 0.99
    weight_decay: 0.0005
    resume: frrnB_cityscapes_best_model.pkl
    visdom: False
