model:
    arch: frrnB
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    path: /home/hovo/datasets
training:
    n_workers: 64
    train_iters: 45000
    batch_size: 2
    val_interval: 500
    print_interval: 25
    optimizer:
        name: adam
        lr: 0.001
    l_rate: 0.001
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
        name: 'multi_step'
        milestones: [10000,30000]
        gamma: 0.1
    momentum: 0.99
    weight_decay: 0.0005
    resume: frrnB_cityscapes_best_model.pkl
    visdom: False
