model:
    arch: unet
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 1024
    img_cols: 2048
    path: ../data/cityscapes
training:
    train_iters: 89250  # 60 epochs at batchsize=2
    batch_size: 2
    val_interval: 500
    print_interval: 25
    optimizer:
        lr: 1.0e-3
        name: adam
    lr_schedule:
        name: poly_lr
        max_iter: 89250
    momentum: 0.99
    weight_decay: 0.0005
    resume: unet_cityscapes_best_model.pkl
    visdom: False
    n_workers: 2
    loss:
        name: cross_entropy
    augmentations:
        hue: 0.1
        brightness: 0.3
        saturation: 0.3
        rcrop: [1008, 2032]
        hflip: 0.5

